name: 'Run sqlfluff with reviewdog'
description: '🐶 Run sqlfluff with reviewdog on pull requests to improve code review experience.'
author: 'Alexander Wornast'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'

  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''

  ### Flags for dbt ###
  dbt_adapter_version:
    default: 1.7.4
  dbt_core_version: 
    default: 1.7.14
  dbt_profiles_dir:
    default: .
  dbt_project_dir:
    default: ./dbt
  dbt_target:
    default: snowflake

  ### Flags for sqlfluff ###
  sqlfluff_version:
    default: 3.0.6
  sqlfluff_templater:
    description: templater for the sql
    default: dbt
  sqlfluff_dialect: 
    description: dialect of the sql
    default: snowflake

runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'check'
  color: 'blue'
