name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-check:
    name: runner / sqlfluff (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          locale: "UK"

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / sqlfluff (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          locale: "UK"
          dbt_project_dir: ./testdata/dbt

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / sqlfluff (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          locale: "UK"
          reviewdog_flags: -filter-mode=file -fail-on-error
